Program Sample1;
{
  Sample program to show off KISS15 - a simple compiler for Pascal/2
}
  procedure demo;
  begin
    WriteLn('Inside Demo!');
  end;

var
  a,b : integer;
begin
  WriteLn('Sample program to demonstrate Power Pascal');
  Write('Sample ASCII String: ');

  for a := 65 to 90 do
    Emit(A);

  WriteLn;

  WriteLn('We will now call "demo" ');

  Demo;

  WriteLn('That wasn''t so bad, was it?');
end.

